import { useState } from "react";
import DetalleVehiculo from "./DetalleVehiculo.jsx";
import "./Galeria.css";
function Galeria({ marca }) {
  const [vehiculoSeleccionado, setVehiculoSeleccionado] = useState(null);
  // lista de vehículos (agrega/edita según tus imágenes en /public/modelos/)
  const vehiculos = [
  { 
    marca: "Volkswagen", 
    modelo: "Golf", 
    año: 2021, 
    precio: 18000, 
    imagen2: "/modeloU/1volkswagen.png" ,
    imagen: "/modelos/1volkswagenLateral.png", 
    motor: "1.4L TSI",
    tipoMotor: "Gasolina, Turbo",
    transmision: "DSG 7 vel.", 
    combustible: "Gasolina", 
    color: "Rojo", 
    puertas: 5, 
    potencia: "150 HP",
    tipo: "Hatchback",
    asientos: 5,
    traccion: "FWD",
    consumoCiudad: "6.5 L/100km",
    consumoCarretera: "4.8 L/100km",
    aceleracion: "8.5 seg" 
  },
  { 
    marca: "Volkswagen", 
    modelo: "Passat", 
    año: 2019, 
    precio: 20000, 
    imagen2: "/modeloU/1VOLKSWAGENPASAT.png", 
    imagen: "/modelos/1VOLKSWAGENPASAT LATERAL.png", 
    motor: "2.0L TSI", 
    tipoMotor: "Gasolina, Turbo",
    transmision: "DSG 6 vel.", 
    combustible: "Gasolina", 
    color: "Negro", 
    puertas: 4, 
    potencia: "190 HP",
    tipo: "Sedán",
    asientos: 5,
    traccion: "FWD",
    consumoCiudad: "8.1 L/100km",
    consumoCarretera: "5.5 L/100km",
    aceleracion: "7.1 seg"
  },
  { 
    marca: "Mercedes", 
    modelo: "Clase A", 
    año: 2022, 
    precio: 30000, 
    imagen2: "/modeloU/2MBClaseA.png", 
    imagen: "/modelos/2MBClaseALateral.png", 
    motor: "1.3L Turbo", 
    tipoMotor: "Gasolina, Turbo",
    transmision: "Automática 7 vel.", 
    combustible: "Gasolina", 
    color: "Plata", 
    puertas: 5, 
    potencia: "163 HP",
    tipo: "Hatchback",
    asientos: 5,
    traccion: "FWD",
    consumoCiudad: "7.0 L/100km",
    consumoCarretera: "5.1 L/100km",
    aceleracion: "8.1 seg"
  },
  { 
    marca: "Mercedes", 
    modelo: "Clase C", 
    año: 2020, 
    precio: 35000, 
    imagen2: "/modeloU/2MBClaseC.png", 
    imagen: "/modelos/2MBClaseClateral.png", 
    motor: "2.0L Turbo", 
    tipoMotor: "Gasolina, Turbo",
    transmision: "Automática 9 vel.", 
    combustible: "Gasolina", 
    color: "Blanco", 
    puertas: 4, 
    potencia: "255 HP",
    tipo: "Sedán",
    asientos: 5,
    traccion: "RWD",
    consumoCiudad: "9.5 L/100km",
    consumoCarretera: "6.2 L/100km",
    aceleracion: "5.9 seg"
  },
  { 
    marca: "Nissan", 
    modelo: "Sentra", 
    año: 2021, 
    precio: 17000, 
    imagen2: "/modeloU/3nisancentraa.png", 
    imagen: "/modelos/3nisancentraLateral.png", 
    motor: "1.6L", 
    tipoMotor: "Gasolina",
    transmision: "Automática CVT", 
    combustible: "Gasolina", 
    color: "Gris", 
    puertas: 4, 
    potencia: "122 HP",
    tipo: "Sedán",
    asientos: 5,
    traccion: "FWD",
    consumoCiudad: "7.8 L/100km",
    consumoCarretera: "6.0 L/100km",
    aceleracion: "10.4 seg"
  },
  { 
    marca: "Nissan", 
    modelo: "Altima", 
    año: 2021, 
    precio: 17000, 
    imagen2: "/modeloU/3nissanaltima.png", 
    imagen: "/modelos/3nissanaltimaLateral.png", 
    motor: "1.6L", 
    tipoMotor: "Gasolina",
    transmision: "Automática CVT", 
    combustible: "Gasolina", 
    color: "Gris", 
    puertas: 4, 
    potencia: "122 HP",
    tipo: "Sedán",
    asientos: 5,
    traccion: "FWD",
    consumoCiudad: "7.8 L/100km",
    consumoCarretera: "6.0 L/100km",
    aceleracion: "10.4 seg"
  },
  { 
    marca: "Mazda", 
    modelo: "Mazda 3", 
    año: 2022, 
    precio: 21000, 
    imagen2: "/modeloU/4Mazda3.png", 
    imagen: "/modelos/4Mazda3lateral.png", 
    motor: "2.0L Skyactiv", 
    tipoMotor: "Gasolina, Skyactiv",
    transmision: "Automática 6 vel.", 
    combustible: "Gasolina", 
    color: "Azul", 
    puertas: 4, 
    potencia: "155 HP",
    tipo: "Sedán",
    asientos: 5,
    traccion: "FWD",
    consumoCiudad: "8.5 L/100km",
    consumoCarretera: "6.1 L/100km",
    aceleracion: "8.8 seg"
  },
  { 
    marca: "Mazda", 
    modelo: "Mazda CX-5", 
    año: 2022, 
    precio: 21000, 
    imagen2: "/modeloU/4MazdaCX-5.png", 
    imagen: "/modelos/4MazdaCX-5lateral.png", 
    motor: "2.0L Skyactiv", 
    tipoMotor: "Gasolina, Skyactiv",
    transmision: "Automática 6 vel.", 
    combustible: "Gasolina", 
    color: "Azul", 
    puertas: 4, 
    potencia: "155 HP",
    tipo: "SUV",
    asientos: 5,
    traccion: "AWD",
    consumoCiudad: "9.2 L/100km",
    consumoCarretera: "7.3 L/100km",
    aceleracion: "9.8 seg"
  },
  { 
    marca: "Honda", 
    modelo: "Civic", 
    año: 2021, 
    precio: 19000, 
    imagen2: "/modeloU/5Civic.png", 
    imagen: "/modelos/5CivicLateral.png", 
    motor: "2.0L", 
    tipoMotor: "Gasolina, i-VTEC",
    transmision: "CVT", 
    combustible: "Gasolina", 
    color: "Negro", 
    puertas: 4, 
    potencia: "158 HP",
    tipo: "Sedán",
    asientos: 5,
    traccion: "FWD",
    consumoCiudad: "7.5 L/100km",
    consumoCarretera: "5.9 L/100km",
    aceleracion: "8.3 seg"
  },
  { 
    marca: "Honda", 
    modelo: "Accord", 
    año: 2021, 
    precio: 19000, 
    imagen2: "/modeloU/5HondaAccord.png", 
    imagen: "/modelos/5HondaAccordLateral.png", 
    motor: "2.0L", 
    tipoMotor: "Gasolina, i-VTEC",
    transmision: "CVT", 
    combustible: "Gasolina", 
    color: "Negro", 
    puertas: 4, 
    potencia: "158 HP",
    tipo: "Sedán",
    asientos: 5,
    traccion: "FWD",
    consumoCiudad: "7.5 L/100km",
    consumoCarretera: "5.9 L/100km",
    aceleracion: "8.3 seg"
  },
  { 
    marca: "Lexus", 
    modelo: "IS 300", 
    año: 2022, 
    precio: 38000, 
    imagen2: "/modeloU/6LexusIS 300.png", 
    imagen: "/modelos/6LexusIS 300Lateral.png", 
    motor: "2.0L Turbo", 
    tipoMotor: "Gasolina, Turbo",
    transmision: "Automática 8 vel.", 
    combustible: "Gasolina", 
    color: "Blanco", 
    puertas: 4, 
    potencia: "241 HP",
    tipo: "Sedán",
    asientos: 5,
    traccion: "RWD",
    consumoCiudad: "10.0 L/100km",
    consumoCarretera: "7.5 L/100km",
    aceleracion: "6.9 seg"
  },
  { 
    marca: "Lexus", 
    modelo: "RX 350", 
    año: 2022, 
    precio: 38000, 
    imagen2: "/modeloU/6LexusLSRX 350.png", 
    imagen: "/modelos/6LexusLSRX 350LATERAL.png", 
    motor: "2.0L Turbo", 
    tipoMotor: "Gasolina, Turbo",
    transmision: "Automática 8 vel.", 
    combustible: "Gasolina", 
    color: "Blanco", 
    puertas: 4, 
    potencia: "241 HP",
    tipo: "SUV",
    asientos: 5,
    traccion: "AWD",
    consumoCiudad: "11.2 L/100km",
    consumoCarretera: "8.5 L/100km",
    aceleracion: "7.7 seg"
  },
  { 
    marca: "Lamborghini", 
    modelo: "Aventador", 
    año: 2021, 
    precio: 200000, 
    imagen2: "/modeloU/7LGAventador.png", 
    imagen: "/modelos/7LGAventadorLateral.png", 
    motor: "5.2L V10", 
    tipoMotor: "Gasolina, V10",
    transmision: "Automática 7 vel.", 
    combustible: "Gasolina", 
    color: "Amarillo", 
    puertas: 2, 
    potencia: "610 HP",
    tipo: "Deportivo",
    asientos: 2,
    traccion: "AWD",
    consumoCiudad: "25.0 L/100km",
    consumoCarretera: "15.0 L/100km",
    aceleracion: "2.9 seg"
  },
  { 
    marca: "Lamborghini", 
    modelo: "Huracán", 
    año: 2021, 
    precio: 200000, 
    imagen2: "/modeloU/7LGHuracán.png", 
    imagen: "/modelos/7LGHuracánLateral.png", 
    motor: "5.2L V10", 
    tipoMotor: "Gasolina, V10",
    transmision: "Automática 7 vel.", 
    combustible: "Gasolina", 
    color: "Amarillo", 
    puertas: 2, 
    potencia: "610 HP",
    tipo: "Deportivo",
    asientos: 2,
    traccion: "AWD",
    consumoCiudad: "25.0 L/100km",
    consumoCarretera: "15.0 L/100km",
    aceleracion: "2.9 seg"
  },
  { 
    marca: "BMW", 
    modelo: "Serie 3", 
    año: 2021, 
    precio: 33000, 
    imagen2: "/modeloU/8BMWSerie 3.png", 
    imagen: "/modelos/8BMWSerie 3LATERAL.png", 
    motor: "2.0L Turbo", 
    tipoMotor: "Gasolina, Turbo",
    transmision: "Automática 8 vel.", 
    combustible: "Gasolina", 
    color: "Gris", 
    puertas: 4, 
    potencia: "255 HP",
    tipo: "Sedán",
    asientos: 5,
    traccion: "RWD",
    consumoCiudad: "8.8 L/100km",
    consumoCarretera: "6.5 L/100km",
    aceleracion: "5.6 seg"
  },
  { 
    marca: "BMW", 
    modelo: "X5", 
    año: 2019, 
    precio: 50000, 
    imagen2: "/modeloU/8BMWX5.png", 
    imagen: "/modelos/8BMWX5LATERAL.png", 
    motor: "3.0L", 
    tipoMotor: "Gasolina",
    transmision: "Automática 8 vel.", 
    combustible: "Gasolina", 
    color: "Negro", 
    puertas: 5, 
    potencia: "335 HP",
    tipo: "SUV",
    asientos: 5,
    traccion: "AWD",
    consumoCiudad: "11.5 L/100km",
    consumoCarretera: "8.7 L/100km",
    aceleracion: "5.3 seg"
  }
];
  // filtrar por la marca recibida (case-insensitive)
   const filtrados = vehiculos.filter(v => v.marca === marca);

  if (vehiculoSeleccionado) {
    return (
      <DetalleVehiculo
        vehiculo={vehiculoSeleccionado}
        onVolver={() => setVehiculoSeleccionado(null)}
      />
    );
  }
  return (
    <div className="vehiculo-contenedor">
      {filtrados.map((v, index) => (
        <div key={index} className="vehiculo-card" onClick={() => setVehiculoSeleccionado(v)}>
          <img src={v.imagen} alt={v.modelo} />
          <h3>{v.modelo}</h3>
          <p>Año: {v.año}</p>
          <p>Precio: ${v.precio}</p>
        </div>
      ))}
    </div>
  );
}
export default Galeria;